// constants/MockData.ts
import { Book, User } from '@/types';

export const MOCK_USER: User = {
  id: 1,
  name: 'John Doe',
  email: 'user@puskata.com',
  profile_image: 'https://i.pravatar.cc/150?img=12',
  role: 'user',
  created_at: new Date().toISOString(),
};

export const MOCK_BOOKS: Book[] = [
  {
    id: 1,
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt & David Thomas',
    isbn: '9780201616224',
    publisher: 'Addison-Wesley',
    published_year: 1999,
    category: 'Programming',
    pages: 352,
    language: 'English',
    description: 'A classic book on software engineering best practices and pragmatic approaches to software development.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51W1sBPO7tL.jpg',
    quantity: 5,
    available: 5,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'Clean Code',
    author: 'Robert C. Martin',
    isbn: '9780132350884',
    publisher: 'Prentice Hall',
    published_year: 2008,
    category: 'Programming',
    pages: 464,
    language: 'English',
    description: 'A handbook on writing clean, maintainable, and scalable code with practical examples.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/I/41xShlnTZTL.jpg',
    quantity: 7,
    available: 6,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'Atomic Habits',
    author: 'James Clear',
    isbn: '9780735211292',
    publisher: 'Penguin Random House',
    published_year: 2018,
    category: 'Self Improvement',
    pages: 320,
    language: 'English',
    description: 'A proven framework for building good habits and breaking bad ones.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51Tlm0GZTXL.jpg',
    quantity: 10,
    available: 8,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    title: 'Laskar Pelangi',
    author: 'Andrea Hirata',
    isbn: '9789793062790',
    publisher: 'Bentang Pustaka',
    published_year: 2005,
    category: 'Novel',
    pages: 529,
    language: 'Indonesian',
    description: 'Kisah persahabatan dan perjuangan anak-anak miskin di Belitung yang penuh inspirasi.',
    cover_image: 'https://cdn.gramedia.com/uploads/items/9789793062792.jpg',
    quantity: 8,
    available: 7,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    title: 'Bumi Manusia',
    author: 'Pramoedya Ananta Toer',
    isbn: '9786024246945',
    publisher: 'Lentera Dipantara',
    published_year: 1980,
    category: 'Sejarah',
    pages: 535,
    language: 'Indonesian',
    description: 'Novel sejarah Indonesia yang mengisahkan perjalanan Minke di era kolonial.',
    cover_image: 'https://cdn.gramedia.com/uploads/items/9786024246945_Bumi-Manusia.jpg',
    quantity: 6,
    available: 5,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    isbn: '9780062316097',
    publisher: 'Harper',
    published_year: 2015,
    category: 'History',
    pages: 443,
    language: 'English',
    description: 'A brief history of humankind from the Stone Age to modern times.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51Sn8PEXwcL.jpg',
    quantity: 12,
    available: 10,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const CATEGORIES = [
  'All',
  'Programming',
  'Self Improvement',
  'Novel',
  'Sejarah',
  'History',
  'Science',
  'Biography',
  'Fiction',
];